// SVG icons matching the Breadline/PactoPay design system
// Using simple geometric shapes — no external icon lib needed yet

export const Icons = {
  shield: '🛡️',
  dollar: '💰',
  star: '⭐',
  clock: '🕐',
  check: '✅',
  warning: '⚠️',
  arrowRight: '→',
  arrowLeft: '←',
  chevronDown: '▼',
  plus: '+',
  upload: '📤',
  download: '📥',
  qr: '📱',
  fingerprint: '🔐',
  globe: '🌐',
  lock: '🔒',
  link: '🔗',
  chat: '💬',
  send: '📤',
  close: '✕',
  menu: '☰',
  home: '🏠',
  invoice: '📄',
  history: '📋',
  profile: '👤',
  flag: '🏁',
  camera: '📷',
  file: '📎',
  search: '🔍',
  bell: '🔔',
  settings: '⚙️',
  logout: '🚪',
  copy: '📋',
  share: '📤',
  crypto: '💎',
  bank: '🏦',
  card: '💳',
  paypal: '🅿️',
  xrp: '✖️',
  btc: '₿',
  eth: 'Ξ',
} as const;
