/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        primary: "#00236f",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-error": "#ffffff",
        "surface-tint": "#4059aa",
        "on-primary": "#ffffff",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        secondary: "#006c4a",
        surface: "#faf8ff",
        "on-primary-container": "#90a8ff",
        "on-surface-variant": "#444651",
        "surface-container-highest": "#dae2fd",
        tertiary: "#442100",
        "surface-container": "#eaedff",
        "secondary-fixed": "#85f8c4",
        "outline-variant": "#c5c5d3",
        "on-secondary-container": "#00714e",
        "on-secondary-fixed-variant": "#005137",
        "on-background": "#131b2e",
        "primary-fixed-dim": "#b6c4ff",
        error: "#ba1a1a",
        "tertiary-container": "#653400",
        "primary-fixed": "#dce1ff",
        "secondary-container": "#82f5c1",
        "on-tertiary-container": "#fc922b",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed": "#002114",
        "on-secondary": "#ffffff",
        "surface-dim": "#d2d9f4",
        outline: "#757682",
        "surface-container-low": "#f2f3ff",
        "inverse-surface": "#283044",
        "primary-container": "#1e3a8a",
        "inverse-primary": "#b6c4ff",
        "secondary-fixed-dim": "#68dba9",
        "on-primary-fixed": "#00164e",
        background: "#faf8ff",
        "on-primary-fixed-variant": "#264191",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdcc3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-sm": "1rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        margin: "2rem",
        "space-md": "1rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "margin-sm": "1rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "amount-display-mobile": ["Inter"],
        "amount-display": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "amount-display-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "amount-display": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "title-lg": [
          "18px",
          { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.025em", fontWeight: "600" },
        ],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
