[package]
name = "pactopay-escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "27.0.0"
serde = { version = ">=1.0.185, <1.0.220", default-features = false }
serde_json = { version = ">=1.0.100, <1.0.130", default-features = false, features = ["alloc"] }
memchr = { version = ">=2.5.0, <2.8.0", default-features = false }

[dev-dependencies]
soroban-sdk = { version = "27.0.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
